### ISSUE TITLE
Missing README.md and CONTRIBUTING.md Files for Hacktoberfest

### ISSUE THREAD

**Issue by ayushichoudhary-19** [KhushalYadav535/Todo-website#1]
**Description:**

The project is tagged with Hacktoberfest, indicating that it welcomes contributions from the open-source community. However, it currently lacks both a README.md and CONTRIBUTING.md file. These files are essential for providing guidance to potential contributors, explaining the project's purpose, and establishing contribution guidelines.

**Expected Behavior:**

- A README.md file should be added to the project repository, containing information about the project, how to set it up, and its goals.
- A CONTRIBUTING.md file should be added to outline the contribution process, including how to submit pull requests, coding standards, and other relevant information for contributors.

By adding these files, the project will become more inviting and accessible to potential contributors, aligning with the Hacktoberfest spirit.

**Comment by ankitkumar748846** [comment]
Please assign me this issue

**Comment by ankitkumar748846** [comment]
@ayushichoudhary-19 @KhushalYadav535

**Comment by ayushichoudhary-19** [comment]
@ankitkumar748846 I'm currently in the midst of some exams, which are demanding my full attention until the 26th. I apologize for any inconvenience this may cause regarding the issue. 

If there's a pressing need to address this issue and someone else is available to work on it, please consider marking it as 'up-for-grabs.' I'm absolutely fine with that, and I don't want to hold back the progress of the project due to my current commitments. However if it's still available after 26th, I'll surely be doing it.
